version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=postgres
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_DRIVER_CLASS=Wallabag\CoreBundle\Doctrine\DBAL\Driver\CustomPostgreSQLDriver
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=${WB_PASSWORD}
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@space.abhinavsarkar.net
      - SYMFONY__ENV__DOMAIN_NAME=http://space.abhinavsarkar.net
    depends_on:
      - db
    volumes:
      - ./wallabag/images:/var/www/wallabag/web/assets/images
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  nginx:
    image: nginx:1.15
    environment:
      - NGINX_HOST=space.abhinavsarkar.net
      - NGINX_PORT=80
    depends_on:
      - wallabag
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-log:/var/log/nginx
